# prometheus-test-demo.yaml
apiVersion: apps/v1
kind: Deployment #对象类型
metadata:
  labels:
    app: prometheus-test-demo
  name: prometheus-test-demo
  namespace: nju05
spec:
  replicas: 3 #运行容器的副本数
  selector:
    matchLabels:
      app: prometheus-test-demo
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app: prometheus-test-demo
    spec:
      containers: #docker容器的配置
        - image: harbor.edu.cn/nju05/prometheus-test-demo:{VERSION} #pull镜像的地址,本地测试时注销
          #      - image: demo:latest  # win下本地测试用
          name: prometheus-test-demo
      #      imagePullPolicy: Always # 本地测试用
      imagePullSecrets: # 本地测试时注销
        - name: docker-harbor-nju05 # 本地测试时注销
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-test-demo
  namespace: nju05
  labels:
    app: prometheus-test-demo
spec:
  type: NodePort
  selector:
    app: prometheus-test-demo
  ports:
    - name: tcp
      nodePort: 31999
      protocol: TCP
      port: 8080
      targetPort: 8080
